version: 1
eventstore1:
  url: http://localhost:8090/request/delivery
eventstore2:
  url: http://localhost:8090/request/restaurant
events:
  hostname: bcitacit3855.westus.cloudapp.azure.com
  port: 9092
  topic: events
connecting_kafka:
  retry_count_max: 10
  time_sleep: 5